[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | migrations
    | _build
    | buck-out
    | build
    | dist
  )/
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
virtual_env = "venv"

[flake8]
max-line-length = 79
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules,venv